# Default values for skopeo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: gardendev/skopeo
  tag: "1.41.0-2"
  pullPolicy: IfNotPresent

nameOverride: "garden-util-daemon"
fullnameOverride: "garden-util-daemon"

resources:
  limits:
    cpu: "2"
    memory: "4Gi"
  requests:
    cpu: 200m
    memory: 256Mi

registry:
  hostname: garden-docker-registry

nodeSelector: {}

tolerations: []

affinity: {}
